/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\marches.ts
 * Command: astryx theme build src\theme\marches.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * marches theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { marchesTheme } from './marches';
 *   import './marches.css';
 */
export const marchesTheme = {
  name: 'marches',
  __built: true,
  tokens: {
    "--color-accent": "#D40B61",
    "--color-accent-muted": "#FCE6E8",
    "--color-on-accent": "#FFFFFF",
    "--color-neutral": "light-dark(#25181B1A, #F1DEE133)",
    "--color-background-surface": "#FEFCF8",
    "--color-background-body": "#FBF7EF",
    "--color-overlay": "light-dark(#25181B66, #25181B99)",
    "--color-overlay-hover": "#5C59530F",
    "--color-overlay-pressed": "#5C59531F",
    "--color-background-muted": "#F1E9DA",
    "--color-text-primary": "#221F1F",
    "--color-text-secondary": "#5C5953",
    "--color-text-disabled": "light-dark(#A38B8F, #6F595D)",
    "--color-text-accent": "#B8084F",
    "--color-icon-accent": "#D40B61",
    "--color-icon-primary": "#221F1F",
    "--color-icon-secondary": "#5C5953",
    "--color-icon-disabled": "light-dark(#A38B8F, #6F595D)",
    "--color-background-card": "#FFFFFF",
    "--color-background-popover": "#FFFFFF",
    "--color-background-inverted": "#5C5953",
    "--color-border": "#D7B5A6",
    "--color-border-emphasized": "#5C5953",
    "--color-skeleton": "light-dark(#BEA5A9, #574145)",
    "--color-track": "light-dark(#BEA5A9, #574145)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.4375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.625rem",
    "--font-size-xs": "0.75rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1.0625rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5rem",
    "--font-size-2xl": "1.8125rem",
    "--font-size-3xl": "2.1875rem",
    "--font-size-4xl": "2.625rem",
    "--font-size-5xl": "3.1875rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-normal)",
    "--text-heading-1-leading": "1.3793",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-normal)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-normal)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-normal)",
    "--text-heading-4-leading": "1.4118",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-normal)",
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-normal)",
    "--text-heading-6-leading": "1.6667",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4118",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4118",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4118",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2549",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2381",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2571",
    "--font-family-body": "\"Berling LT Std\", 'Crimson Pro', 'Iowan Old Style', Palatino, Georgia, serif",
    "--font-family-heading": "\"Grenze Gotisch\", 'Pirata One', Georgia, serif",
    "--focus-outline-color": "#D40B61",
    "--color-background-blue": "#C5D6E8",
    "--color-border-blue": "#2F5D8A",
    "--color-icon-blue": "#2F5D8A",
    "--color-text-blue": "#1B3652",
    "--color-background-green": "#C8DEC0",
    "--color-border-green": "#3D7747",
    "--color-icon-green": "#3D7747",
    "--color-text-green": "#1F4226",
    "--color-background-orange": "#EDCCA3",
    "--color-border-orange": "#B0601C",
    "--color-icon-orange": "#B0601C",
    "--color-text-orange": "#63300C",
    "--color-background-yellow": "#E9DA9A",
    "--color-border-yellow": "#957811",
    "--color-icon-yellow": "#957811",
    "--color-text-yellow": "#554304",
    "--color-background-red": "#EBBDB2",
    "--color-border-red": "#A5302A",
    "--color-icon-red": "#A5302A",
    "--color-text-red": "#651912",
    "--color-background-purple": "#D5C6E6",
    "--color-border-purple": "#674889",
    "--color-icon-purple": "#674889",
    "--color-text-purple": "#3C2854",
    "--color-background-gray": "#DAD2C6",
    "--color-border-gray": "#6D6963",
    "--color-icon-gray": "#6D6963",
    "--color-text-gray": "#35322F",
    "--color-background-teal": "#C0DAD7",
    "--color-border-teal": "#408080",
    "--color-icon-teal": "#408080",
    "--color-text-teal": "#1E4747",
    "--color-background-pink": "#F9CBD6",
    "--color-border-pink": "#D40B61",
    "--color-icon-pink": "#D40B61",
    "--color-text-pink": "#78063A"
  },
  localTokens: {
    "--font-family-ui": "Cabin, 'Gill Sans', 'Segoe UI', sans-serif",
    "--color-bar": "#5C5953",
    "--color-on-bar": "#EDE8E0",
    "--color-highlight": "#EC0C6C"
  },
  __localTokenOwners: {
    "--font-family-ui": "marches",
    "--color-bar": "marches",
    "--color-on-bar": "marches",
    "--color-highlight": "marches"
  },
  __localTokenLineage: ["marches"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-none)"
      },
      "variant:blue": {
        "borderTop": "var(--spacing-1) solid var(--color-border-blue)"
      },
      "variant:green": {
        "borderTop": "var(--spacing-1) solid var(--color-border-green)"
      },
      "variant:orange": {
        "borderTop": "var(--spacing-1) solid var(--color-border-orange)"
      },
      "variant:yellow": {
        "borderTop": "var(--spacing-1) solid var(--color-border-yellow)"
      },
      "variant:red": {
        "borderTop": "var(--spacing-1) solid var(--color-border-red)"
      },
      "variant:purple": {
        "borderTop": "var(--spacing-1) solid var(--color-border-purple)"
      },
      "variant:gray": {
        "borderTop": "var(--spacing-1) solid var(--color-border-gray)"
      },
      "variant:teal": {
        "borderTop": "var(--spacing-1) solid var(--color-border-teal)"
      },
      "variant:pink": {
        "borderTop": "var(--spacing-1) solid var(--color-border-pink)"
      }
    },
    "button": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "side-nav-item": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "side-nav-section": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "side-nav-heading": {
      "base": {
        "fontFamily": "var(--font-family-heading)"
      }
    },
    "dialog-header-title-block": {
      "base": {
        "fontFamily": "var(--font-family-heading)"
      }
    },
    "field-label": {
      "base": {
        "fontFamily": "var(--font-family-heading)",
        "letterSpacing": "0.02em"
      }
    },
    "tab": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "token": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "badge": {
      "base": {
        "fontFamily": "var(--font-family-ui)"
      }
    },
    "table-header-cell": {
      "base": {
        "backgroundColor": "var(--color-bar)",
        "color": "var(--color-on-bar)",
        "fontFamily": "var(--font-family-heading)",
        "letterSpacing": "0.04em"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 17,
        "ratio": 1.2
      },
      "body": {
        "family": "Berling LT Std",
        "fallbacks": "'Crimson Pro', 'Iowan Old Style', Palatino, Georgia, serif"
      },
      "heading": {
        "family": "Grenze Gotisch",
        "fallbacks": "'Pirata One', Georgia, serif",
        "weight": "normal",
        "weights": {
          "1": "normal",
          "2": "normal",
          "3": "normal",
          "4": "normal",
          "5": "normal",
          "6": "normal"
        }
      }
    },
    "color": {
      "accent": "#D40B61",
      "neutralStyle": "warm",
      "contrast": "high"
    }
  },

};
