/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/marches.ts
 * Command: astryx theme build src/theme/marches.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * marches theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { marchesTheme } from './marches';
 *   import './marches.css';
 */
export const marchesTheme = {
  name: 'marches',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#5D2A42, #FCB1A6)",
    "--color-accent-muted": "light-dark(#FCB1A6, #5D2A42)",
    "--color-on-accent": "light-dark(#FFF9EC, #2A1220)",
    "--color-neutral": "light-dark(#24181D1A, #EFDEE533)",
    "--color-background-surface": "light-dark(#FFFDF7, #361926)",
    "--color-background-body": "light-dark(#FFF9EC, #2A1220)",
    "--color-overlay": "light-dark(#24181D66, #24181D99)",
    "--color-overlay-hover": "light-dark(#24181D0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#24181D1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#FFDCCC, #4A2637)",
    "--color-text-primary": "light-dark(#5D2A42, #F6E4D8)",
    "--color-text-secondary": "light-dark(#7A4258, #E8C9BC)",
    "--color-text-disabled": "light-dark(#A18B94, #6D5961)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #FFFAFD)",
    "--color-icon-secondary": "light-dark(#3D2B33, #D8C0CA)",
    "--color-icon-disabled": "light-dark(#A18B94, #6D5961)",
    "--color-background-card": "light-dark(#FFFFFF, #40202F)",
    "--color-background-popover": "light-dark(#FFFAFD, #3A2D32)",
    "--color-background-inverted": "light-dark(#24181D, #FFFAFD)",
    "--color-border": "light-dark(#FCB1A6, #5D2A42)",
    "--color-border-emphasized": "light-dark(#5D2A42, #8E5066)",
    "--color-skeleton": "light-dark(#BCA5AE, #554149)",
    "--color-track": "light-dark(#BCA5AE, #554149)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.4375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.625rem",
    "--font-size-xs": "0.75rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1.0625rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5rem",
    "--font-size-2xl": "1.8125rem",
    "--font-size-3xl": "2.1875rem",
    "--font-size-4xl": "2.625rem",
    "--font-size-5xl": "3.1875rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3793",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.3333",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4118",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.4286",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.6667",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4118",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4118",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4118",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.4286",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2549",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2381",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2571",
    "--font-family-body": "Cabin, 'Gill Sans', 'Gill Sans MT', 'Helvetica Neue', Helvetica, sans-serif",
    "--font-family-heading": "\"Almendra SC\", 'EB Garamond', Palatino, Georgia, serif",
    "--color-highlight": "light-dark(#FB6376, #FB6376)"
  },
  localTokens: {
    "--font-family-prose": "'EB Garamond', 'Iowan Old Style', Palatino, Georgia, serif"
  },
  __localTokenOwners: {
    "--font-family-prose": "marches"
  },
  __localTokenLineage: ["marches"],
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 17,
        "ratio": 1.2
      },
      "body": {
        "family": "Cabin",
        "fallbacks": "'Gill Sans', 'Gill Sans MT', 'Helvetica Neue', Helvetica, sans-serif"
      },
      "heading": {
        "family": "Almendra SC",
        "fallbacks": "'EB Garamond', Palatino, Georgia, serif",
        "weight": "bold",
        "weights": {
          "1": "bold",
          "2": "bold",
          "3": "bold"
        }
      }
    },
    "color": {
      "accent": "#5D2A42",
      "neutralStyle": "warm",
      "contrast": "high"
    }
  },

};
