/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\marches.ts
 * Command: astryx theme build src\theme\marches.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/**
 * marches theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { marchesTheme } from './marches';
 *   import './marches.css';
 */
export const marchesTheme = {
  name: 'marches',
  __built: true,
  tokens: {
    "--color-accent": "#D40B61",
    "--color-accent-muted": "#FCE6E8",
    "--color-on-accent": "#FFFFFF",
    "--color-neutral": "light-dark(#25181B1A, #F1DEE133)",
    "--color-background-surface": "#FEFCF8",
    "--color-background-body": "#FBF7EF",
    "--color-overlay": "light-dark(#25181B66, #25181B99)",
    "--color-overlay-hover": "#5C59530F",
    "--color-overlay-pressed": "#5C59531F",
    "--color-background-muted": "#F1E9DA",
    "--color-text-primary": "#221F1F",
    "--color-text-secondary": "#5C5953",
    "--color-text-disabled": "light-dark(#A38B8F, #6F595D)",
    "--color-text-accent": "#B8084F",
    "--color-icon-accent": "#D40B61",
    "--color-icon-primary": "#221F1F",
    "--color-icon-secondary": "#5C5953",
    "--color-icon-disabled": "light-dark(#A38B8F, #6F595D)",
    "--color-background-card": "#FFFFFF",
    "--color-background-popover": "#FFFFFF",
    "--color-background-inverted": "#5C5953",
    "--color-border": "#D7B5A6",
    "--color-border-emphasized": "#5C5953",
    "--color-skeleton": "light-dark(#BEA5A9, #574145)",
    "--color-track": "light-dark(#BEA5A9, #574145)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-family-body": "\"Berling LT Std\", 'Crimson Pro', 'Iowan Old Style', Palatino, Georgia, serif",
    "--font-family-heading": "\"Grenze Gotisch\", 'Pirata One', Georgia, serif",
    "--font-family-code": "Cabin, 'Gill Sans', 'Segoe UI', sans-serif",
    "--focus-outline-color": "#D40B61",
    "--color-background-blue": "#C5D6E8",
    "--color-border-blue": "#2F5D8A",
    "--color-icon-blue": "#2F5D8A",
    "--color-text-blue": "#1B3652",
    "--color-background-green": "#C8DEC0",
    "--color-border-green": "#3D7747",
    "--color-icon-green": "#3D7747",
    "--color-text-green": "#1F4226",
    "--color-background-orange": "#EDCCA3",
    "--color-border-orange": "#B0601C",
    "--color-icon-orange": "#B0601C",
    "--color-text-orange": "#63300C",
    "--color-background-yellow": "#E9DA9A",
    "--color-border-yellow": "#957811",
    "--color-icon-yellow": "#957811",
    "--color-text-yellow": "#554304",
    "--color-background-red": "#EBBDB2",
    "--color-border-red": "#A5302A",
    "--color-icon-red": "#A5302A",
    "--color-text-red": "#651912",
    "--color-background-purple": "#D5C6E6",
    "--color-border-purple": "#674889",
    "--color-icon-purple": "#674889",
    "--color-text-purple": "#3C2854",
    "--color-background-gray": "#DAD2C6",
    "--color-border-gray": "#6D6963",
    "--color-icon-gray": "#6D6963",
    "--color-text-gray": "#35322F",
    "--color-background-teal": "#C0DAD7",
    "--color-border-teal": "#408080",
    "--color-icon-teal": "#408080",
    "--color-text-teal": "#1E4747",
    "--color-background-pink": "#F9CBD6",
    "--color-border-pink": "#D40B61",
    "--color-icon-pink": "#D40B61",
    "--color-text-pink": "#78063A"
  },
  localTokens: {
    "--color-bar": "#5C5953",
    "--color-on-bar": "#EDE8E0",
    "--color-highlight": "#EC0C6C"
  },
  __localTokenOwners: {
    "--color-bar": "marches",
    "--color-on-bar": "marches",
    "--color-highlight": "marches"
  },
  __localTokenLineage: ["marches"],
  components: {
    "blockquote": {
      "base": {
        "fontStyle": "italic"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-none)"
      }
    },
    "button": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "side-nav-item": {
      "base": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--font-size-lg)"
      }
    },
    "dropdown-menu-item": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "side-nav-section": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "side-nav-heading": {
      "base": {
        "fontFamily": "var(--font-family-heading)"
      }
    },
    "dialog-header-title-block": {
      "base": {
        "fontFamily": "var(--font-family-heading)"
      }
    },
    "field-label": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "tab": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "token": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "badge": {
      "base": {
        "fontFamily": "var(--font-family-code)"
      }
    },
    "table-header-cell": {
      "base": {
        "backgroundColor": "var(--color-bar)",
        "color": "var(--color-on-bar)",
        "fontFamily": "var(--font-family-code)",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.06em",
        "textTransform": "uppercase"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "body": {
        "family": "Berling LT Std",
        "fallbacks": "'Crimson Pro', 'Iowan Old Style', Palatino, Georgia, serif"
      },
      "heading": {
        "family": "Grenze Gotisch",
        "fallbacks": "'Pirata One', Georgia, serif"
      },
      "code": {
        "family": "Cabin",
        "fallbacks": "'Gill Sans', 'Segoe UI', sans-serif"
      }
    },
    "color": {
      "accent": "#D40B61",
      "neutralStyle": "warm",
      "contrast": "high"
    }
  },

};
