import React from "react";
import { Icon, addCollection } from "@iconify/react";
import pepicons from "../icons/ui.json";

// Only the icons this app draws: the full Pepicons set is 1.8MB of JSON.
// src/icons/ui.json is generated by notes/gen-icons.mjs.
addCollection(pepicons);

export default function Ico({ name, size = 16 }) {
  return <Icon icon={`pepicons-print:${name}`} width={size} height={size} />;
}
