// Tables from Knave: Second Edition (Ben Milton, Questing Beast LLC, 2024):
// Locations (p10), Structures and Place Traits (p11), City Themes (p46),
// Street Details and Buildings (p47), Factions (p50).
// Knave's mechanics are freely reusable; the tables are the game's mechanics.
// Entries that only point to another table (such as "Color (p. 37)") are left
// out, so every roll is a word in its own right.

export const LOCATIONS = ["Ashland", "Badland", "Bamboo forest", "Basalt columns", "Bay", "Beach", "Bluff", "Bog", "Boulder field", "Brook", "Butte", "Caldera", "Canyon", "Cave", "Cliff", "Cloud forest", "Coniferous forest", "Copse", "Crag", "Crater", "Creek", "Crossing", "Crystals", "Deciduous forest", "Delta", "Dunes", "Dust bowl", "Fen", "Fjord", "Floodplain", "Gas vent", "Geyser", "Glacier", "Gorge", "Grotto", "Grove", "Gulch", "Heath", "Highland", "Hollow", "Hoodoo", "Hot spring", "Ice sheet", "Jungle", "Knoll", "Lagoon", "Lair", "Lake", "Lakebed", "Lava field", "Lava tube", "Loch", "Mangrove swamp", "Marsh", "Meadow", "Mesa", "Mire", "Moor", "Mountain", "Mud plain", "Oasis", "Oil seep", "Pass", "Pasture", "Petrified forest", "Pit", "Plateau", "Pond", "Prairie", "Quicksand", "Rainforest", "Rapids", "Ravine", "Ridge", "River", "Riverland", "Rockslide", "Salt flat", "Salt marsh", "Savanna", "Scree slope", "Scrubland", "Sinkhole", "Spring", "Steppe", "Stream", "Sulfur spring", "Swamp", "Taiga", "Tar pit", "Thicket", "Tundra", "Valley", "Volcanic plain", "Volcano", "Wasteland", "Waterfall", "Wetlands", "Whirlpool"];

export const STRUCTURES = ["Abbey", "Altar", "Amphitheater", "Aqueduct", "Archive", "Asylum", "Bandit camp", "Barn", "Battlefield", "Bell tower", "Bonfire", "Bower", "Brazier", "Cairn", "Cart track", "Castle", "Catacomb", "Chapel", "City", "Cistern", "Convent", "Crossroads", "Dam", "Dirt road", "Dolmen", "Farm", "Ferry", "Festival", "Fishing hut", "Ford", "Forester lodge", "Fort", "Gallows", "Garden", "Garrison", "Gate", "Gibbet", "Graveyard", "Hamlet", "Henge", "Hermitage", "Hideout", "Highway", "Hunter's camp", "Hunting lodge", "Keep", "Library", "Lighthouse", "Logging camp", "Manor", "Market", "Memorial", "Mill", "Mine", "Monastery", "Monolith", "Monument", "Mule track", "Obelisk", "Orchard", "Outpost", "Paved road", "Pen", "Pilgrim camp", "Pillar", "Port", "Prison", "Pyramid", "Refugee camp", "Road", "Ruin", "Shepherd hut", "Shrine", "Signal tower", "Stable", "Statue", "Stone bridge", "Stone circle", "Surveyor camp", "Tavern", "Temple", "Toll house", "Tomb", "Tower", "Town", "Trader camp", "Trail", "Village", "Wall", "Watchtower", "Watermill", "Well", "Windmill", "Wizard tower", "Wooden bridge"];

export const TRAITS = ["Ashen", "Bewitching", "Black", "Blessed", "Blighted", "Bloody", "Boiling", "Bright", "Broken", "Buried", "Burning", "Charred", "Collapsed", "Crawling", "Crimson", "Crumbling", "Crystalline", "Cursed", "Dark", "Dead", "Desolate", "Disorienting", "Divine", "Doomed", "Echoing", "Eerie", "Elder", "Eldritch", "Endless", "Filthy", "Flooded", "Forbidden", "Forgotten", "Frozen", "Ghostly", "Glittering", "Gloomy", "Grim", "Haunted", "Hidden", "Holy", "Humid", "Infernal", "Infested", "Jagged", "Labyrinthine", "Living", "Loathsome", "Mechanical", "Misty", "Murmuring", "Mysterious", "Oozing", "Overgrown", "Perilous", "Petrified", "Phantasmal", "Phasing", "Pristine", "Ravaged", "Ravenous", "Restless", "Revered", "Savage", "Scorching", "Screaming", "Shadowy", "Shifting", "Shivering", "Shrouded", "Silent", "Singing", "Sinister", "Sinking", "Sleeping", "Stony", "Sunken", "Swamped", "Swarming", "Sweltering", "Terrifying", "Thorny", "Thundering", "Twisting", "Unquiet", "Vandalized", "Vast", "Watching", "Whispering", "Windy", "Withered", "Wondrous", "Writhing"];

export const CITY_THEMES = ["Alchemy", "Aristocracy", "Art", "Asylums", "Banking", "Baths", "Begging", "Bells", "Brewing", "Bridges", "Bureaucracy", "Business", "Canals", "Catacombs", "Cats", "Courts", "Crime families", "Cults", "Dancing", "Dining", "Drinking", "Dueling", "Fashion", "Festivals", "Feuds", "Fishing", "Flowers", "Fortifications", "Fountains", "Gambling", "Gangs", "Gardens", "Government", "Guilds", "Horses", "Hunger", "Industry", "Inventions", "Leisure", "Libraries", "Livestock", "Marketplaces", "Mausoleums", "Medicine", "Mercenaries", "Military", "Monasteries", "Monuments", "Museums", "Music", "Opulence", "Perfume", "Printing", "Prisons", "Punishment", "Rats", "Ravens", "Refuse", "Rituals", "Ruins", "Sacrifices", "Science", "Shipyards", "Slavery", "Slums", "Smithing", "Smoke", "Song", "Spices", "Spores", "Steam power", "Temples", "Textiles", "Theaters", "Thievery", "Towers", "Training", "Trees", "Universities", "Wizardry"];

export const STREET_DETAILS = ["Aqueduct", "Arcade", "Archway", "Awnings", "Balconies", "Barricades", "Benches", "Bonfire", "Bricklayers", "Bridge", "Broken glass", "Canal", "Carpets", "Carriages", "Carts", "Catwalks", "Checkpoint", "Children", "Chimneys", "Clergy", "Climbable walls", "Clotheslines", "Compost", "Crates", "Crowd", "Crumbling walls", "Dead end", "Dusty", "Entertainers", "Fence", "Flooding", "Food stalls", "Fountain", "Fresh paint", "Fungi", "Gardens", "Gas leak", "Gates", "Graffiti", "Gravel", "Guards", "Hay bales", "Hot coals", "Ladders", "Lampposts", "Lanterns", "Livestock", "Long steps", "Manure pile", "Mud", "Narrow", "Nobility", "Oil spill", "Overgrown", "Palanquins", "Pickpockets", "Piles of rags", "Pollen clouds", "Pool", "Posters", "Roof access", "Roots", "Ropes", "Roundabout", "Sand pile", "Scaffolding", "Sewage", "Sewer access", "Shrine", "Sinkhole", "Skybridge", "Smoke", "Spilled fruit", "Statues", "Steam", "Steep roofs", "Steep streets", "Stepping stones", "Street cleaners", "Street criers", "Teens", "Tents", "Thugs", "Torches", "Torn up street", "Trees", "Tunnel", "Vermin swarms", "Weapon stalls", "Well", "Wet cement", "Wine spill"];

export const BUILDINGS = ["Academy", "Alchemist", "Apothecary", "Archive", "Armorer", "Art dealer", "Asylum", "Baker", "Bank", "Barber", "Bathhouse", "Blacksmith", "Bookbinder", "Bookseller", "Boyer", "Brewery", "Butcher", "Candlemaker", "Carpenter", "Castle", "Catacombs", "Chandler", "Cheesemaker", "Clockmaker", "Clothier", "Cobbler", "Courthouse", "Criminal den", "Curiosity shop", "Dock", "Dyer", "Fighting pit", "Fletcher", "Fortune teller", "Furrier", "Gallery", "Gambling hall", "Garden", "Gatehouse", "Glassworks", "Goldsmith", "Guildhall", "Haberdashery", "Hospital", "Jeweler", "Law office", "Leatherworks", "Library", "Locksmith", "Lounge", "Manor", "Marketplace", "Mason", "Menagerie", "Monastery", "Moneylender", "Museum", "Observatory", "Opera house", "Orphanage", "Outfitter", "Palace", "Park", "Physician", "Potter", "Printer", "Prison", "Restaurant", "Rope maker", "Saddler", "Sewers", "Shipyards", "Shrine", "Slaughterhouse", "Stables", "Stockyard", "Stonecarver", "Tailor", "Tannery", "Tattooist", "Taxidermist", "Temple", "Theater", "Tobacconist", "Townhouse", "University", "Veterinarian", "Warehouse", "Watchtower", "Watermill", "Weapon smith", "Weaver", "Windmill", "Winery", "Wizard's tower", "Workshop"];

export const FACTIONS = ["Actors' guild", "Angelic army", "Art movement", "Art school", "Assassins' guild", "Bandit troop", "Banking corp", "Barbarian horde", "Bards' guild", "Beggars' guild", "Big game hunters", "Burgling crew", "Chimney sweeps", "Circus troupe", "City council", "City guard", "Convent", "Counterfeiters", "Courtier faction", "Crafting guild", "Crime family", "Cult fanatics", "Debate society", "Demonic army", "Deserter band", "Dragon cult", "Druid circle", "Dungeoneer guild", "Elite warriors", "Explorer's club", "Fencing school", "Fight club", "Fraternity", "Free company", "Gambling ring", "Ghost society", "Gladiator league", "Gourmand club", "Gravediggers", "Healing order", "Heist crew", "Heretical sect", "High council", "Hired muscle", "Illuminati", "Inquisition", "Knightly order", "Living machines", "Local watch", "Mad scientists", "Merchant cartel", "Midwife union", "Militia", "Mining company", "Monastery", "Monster hunters", "Mothers", "Mutants", "National church", "Naval crew", "Necromancers", "Noble house", "Officers' club", "Oracles' circle", "Outlander clan", "Peacekeepers", "Philosophy club", "Pirate crew", "Poachers", "Social movement", "Political party", "Ranger squad", "Religious sect", "Resistance", "Royal army", "Royal house", "Scholar's circle", "School faculty", "Secret society", "Sewer people", "Smuggling ring", "Sports league", "Sports team", "Spy network", "Street artists", "Street gang", "Street musicians", "Student union", "Terrorist cell", "Thieves' guild", "Trade company", "Urchin swarm", "Vampire clan", "Veteran society", "Vigilante league", "Warlock pact", "Werewolf pack", "Witch coven", "Wizard school", "Zombie horde"];
